[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Packages.gd', 'php82Packages.pdo', 'php82Packages.pdo_pgsql', 'php82Packages.mbstring', 'php82Packages.curl', 'php82Packages.xml', 'php82Packages.bcmath', 'php82Packages.openssl', 'php82Packages.zip', 'php82Packages.intl']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php artisan optimize:clear']
cmds = ['php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'